// vue-apps/app-two/App.vue
<template>
  <div :class="$style.app">
    <h1>This is App Two</h1>
    <app-link base="/mixspa-example/react-apps" to="/">React App Home</app-link>
    <app-link base="/mixspa-example/react-apps" to="/app-one">React App One</app-link>
    <app-link base="/mixspa-example/react-apps" to="/app-two">React App Two</app-link>
  </div>
</template>

<script>
import { AppLink } from '@mixspa/vue'

export default {
  props: ['baseUrl'],
  components: { 'app-link': AppLink }
}
</script>

<style lang="scss" module>
.app {
  padding: 30px;
  font-size: 18px;
  color: #2c3e50;
}
</style>

// react-apps/nav-app/App.js
import React from 'react';
import PropTypes from 'prop-types';
import { AppLink } from '@mixspa/react';
import style from './App.scss';

const App = ({ baseUrl }) => (
  <div className={ style.navBar }>
    <ul>
      <li>
        <AppLink base={ baseUrl } to="/">Home</AppLink>
      </li>
      <li>
        <AppLink base={ baseUrl } to="/app-one">App One</AppLink>
      </li>
      <li>
        <AppLink base={ baseUrl } to="/app-two">App Two</AppLink>
      </li>
    </ul>
  </div>
);

App.propTypes = {
  baseUrl: PropTypes.string.isRequired
};

export default App;
