// vue-apps/nav-app/App.vue
<template>
  <ul :class="$style.nav">
    <li><app-link :base="baseUrl" to="/">Home</app-link></li>
    <li><app-link :base="baseUrl" to="/app-one">App One</app-link></li>
    <li><app-link :base="baseUrl" to="/app-two">App Two</app-link></li>
  </ul>
</template>

<script>
import { AppLink } from '@mixspa/vue'

export default {
  props: ['baseUrl'],
  components: { 'app-link': AppLink }
}
</script>

<style lang="scss" module>
.nav {
  li {
    line-height: 50px;
    text-align: center;
    text-decoration: none;
  }
}
</style>

// react-apps/nav-app/App.js
import React from 'react';
import PropTypes from 'prop-types';
import { AppLink } from '@mixspa/react';
import style from './App.scss';

const App = ({ baseUrl }) => (
  <div className={ style.navBar }>
    <ul>
      <li>
        <AppLink base={ baseUrl } to="/">Home</AppLink>
      </li>
      <li>
        <AppLink base={ baseUrl } to="/app-one">App One</AppLink>
      </li>
      <li>
        <AppLink base={ baseUrl } to="/app-two">App Two</AppLink>
      </li>
    </ul>
  </div>
);

App.propTypes = {
  baseUrl: PropTypes.string.isRequired
};

export default App;
