// react-apps/app-one/App.js
import React from 'react';
import { AppLink } from '@mixspa/react';
import classNames from 'classnames/bind';
import styles from './App.scss';

let cx = classNames.bind(styles);

const App = () => (
  <div className={ cx('app') }>
    <div>I am App One</div>
    <AppLink base="/mixspa-example/vue-apps" to="/app-one">Vue App One</AppLink>
  </div>
);

export default App;

// vue-apps/app-one/App.vue
<template>
  <div :class="$style.app">
    <h1>This is App One</h1>
    <app-link :class="$style.link" base="/mixspa-example/react-apps" to="/app-one">React App One</app-link>
  </div>
</template>

<script>
import { AppLink } from '@mixspa/vue'

export default {
  props: ['baseUrl'],
  components: { 'app-link': AppLink }
}
</script>

<style lang="scss" module>
.app {
  padding: 30px;
  font-size: 18px;
  color: #2c3e50;

  .link {
    display: block;
    line-height: 30px;
  }
}
</style>
