// vue-apps/app-two/App.vue
<template>
  <div :class="$style.app">
    <h1>This is App Two</h1>
    <app-link base="/mixspa-example/react-apps" to="/">React App Home</app-link>
  </div>
</template>

<script>
import { AppLink } from '@mixspa/vue'

export default {
  props: ['baseUrl'],
  components: { 'app-link': AppLink }
}
</script>

<style lang="scss" module>
.app {
  padding: 30px;
  font-size: 18px;
  color: #2c3e50;
}
</style>

// react-apps/app-two/App.js
import React from 'react';
import { AppLink } from '@mixspa/react';
import classNames from 'classnames/bind';
import styles from './App.scss';

let cx = classNames.bind(styles);

const App = () => (
  <div className={ cx('app') }>
    <div>I am App Two</div>
    <AppLink base="/mixspa-example/vue-apps" to="/app-two">Vue App Two</AppLink>
  </div>
);

export default App;
